apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "medusa-backend.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  NODE_ENV: {{ .Values.medusa.env.NODE_ENV | quote }}
  PORT: {{ .Values.medusa.env.PORT | quote }}
  REDIS_URL: {{ include "medusa-backend.redisUrl" . }}
  STORE_CORS: {{ .Values.medusa.env.STORE_CORS | default "https://docs.medusajs.com" | quote }}
  ADMIN_CORS: {{ .Values.medusa.env.ADMIN_CORS | default "https://docs.medusajs.com" | quote }}
  AUTH_CORS: {{ .Values.medusa.env.AUTH_CORS | default "https://docs.medusajs.com" | quote }}
