{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "medusa-backend.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncWaves.secret }}"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ include "medusa-backend.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.parameters.jwtSecret }}
    - secretKey: COOKIE_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.parameters.cookieSecret }}
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.parameters.postgresPassword }}
{{- end }}
