apiVersion: v1
kind: Service
metadata:
  name: {{ include "medusa-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: medusa
    {{- include "medusa-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.medusa.service.type }}
  ports:
    - port: {{ .Values.medusa.service.port }}
      targetPort: {{ .Values.medusa.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: medusa
    {{- include "medusa-backend.selectorLabels" . | nindent 4 }}
