{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "medusa-backend.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    {{- include "medusa-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
      protocol: TCP
      name: postgres
  selector:
    app: postgres
    {{- include "medusa-backend.selectorLabels" . | nindent 4 }}
{{- end }}
