{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "medusa-backend.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
    {{- include "medusa-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
      name: redis
  selector:
    app: redis
    {{- include "medusa-backend.selectorLabels" . | nindent 4 }}
{{- end }}
